[OpenDartReader - 비상장 기업 데이터 조회와 활용]
- https://github.com/FinanceData/OpenDartReader
- https://nbviewer.org/gist/FinanceData/12440c298682c44758e4789909a3f333

In [11]:
# !pip install opendartreader

In [10]:
import OpenDartReader
import pandas as pd

In [11]:
# Open DART API KEY 설정
api_key='e10b8471ac01a418f8888d36542cd39dc82bc330'
dart = OpenDartReader(api_key)

In [12]:
# [비바리퍼블리카] (송금서비스 토스로 유명한), 공시(감사보고서) 목록
df = dart.list('비바리퍼블리카', start='1900') 
df

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,01212921,비바리퍼블리카,,E,사업보고서 (2022.12),20230331003986,비바리퍼블리카,20230331,연
1,01212921,비바리퍼블리카,,E,[기재정정]분기보고서 (2022.09),20230209000527,비바리퍼블리카,20230209,
2,01212921,비바리퍼블리카,,E,[기재정정]반기보고서 (2022.06),20230209000508,비바리퍼블리카,20230209,
3,01212921,비바리퍼블리카,,E,주요사항보고서(유상증자결정),20221116000218,비바리퍼블리카,20221116,
4,01212921,비바리퍼블리카,,E,[기재정정]주요사항보고서(유상증자결정),20221031000418,비바리퍼블리카,20221031,
5,01212921,비바리퍼블리카,,E,주요사항보고서(유상증자결정),20221020000382,비바리퍼블리카,20221020,
6,01212921,비바리퍼블리카,,E,주요사항보고서(유상증자결정),20220825000567,비바리퍼블리카,20220825,
7,01212921,비바리퍼블리카,,E,주요사항보고서(유상증자결정),20220720000316,비바리퍼블리카,20220720,
8,01212921,비바리퍼블리카,,E,분기보고서 (2022.03),20220530000844,비바리퍼블리카,20220530,
9,01212921,비바리퍼블리카,,E,사업보고서 (2021.12),20220331003427,비바리퍼블리카,20220331,연
10,01212921,비바리퍼블리카,,E,연결감사보고서 (2020.12),20210406000710,삼일회계법인,20210406,
11,01212921,비바리퍼블리카,,E,감사보고서 (2020.12),20210406000707,삼일회계법인,20210406,
12,01212921,비바리퍼블리카,,E,감사보고서 (2019.12),20200410003129,삼일회계법인,20200410,
13,01212921,비바리퍼블리카,,E,감사보고서 (2018.12),20190412002776,삼일회계법인,20190412,
14,01212921,비바리퍼블리카,,E,감사보고서 (2017.12),20180413001411,삼일회계법인,20180413,

In [13]:
# [쿠팡] "연결감사보고서 (2019.12)" 20200414000766 (삼일회계법인)
# http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20200414000766
html_text = dart.document('20200414000766')
df_list = pd.read_html(html_text)
df_list[15] # 연결포괄손익계산서

C:\Users\jjgus\anaconda3\lib\site-packages\bs4\builder\__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

                   과 목        주석   제 7 (당)기     제 6 (전)기
0               Ⅰ. 매출액  182324.0    7153094      4354586
1                 매출원가    1924.0    5950017      4142781
2             영업 일반관리비  192324.0    1923606      1339769
3              Ⅱ. 영업손실       NaN  (720,529)  (1,127,964)
4                 기타수익       NaN       1782          436
5                 기타비용       NaN       1481          666
6                 금융수익     520.0      50396        19338
7                 금융비용     520.0      54155        33450
8       Ⅲ. 법인세비용차감전순손실       NaN  (723,987)  (1,142,306)
9             Ⅳ. 법인세비용      14.0      (747)         2331
10            Ⅴ. 당기순손실       NaN  (723,240)  (1,144,637)
11          지배기업 소유주지분       NaN  (723,240)  (1,144,637)
12               비지배지분       NaN          -            -
13           Ⅵ. 기타포괄손실       NaN   (10,504)      (2,826)
14  당기손익으로 재분류되지 않는 항목       NaN   (10,504)      (2,826)
15      순확정급여부채의 재측정요소      13.0   (10,504)      (2,826)
16          Ⅶ. 당기총포괄손실       NaN  (733,744)  (1,147,463)
17          지배기업 소유주지분       NaN  (733,744)  (1,147,463)
18               비지배지분       NaN          -            -

비상장 회사의 공시보고서 목록

In [14]:
df = dart.list('비바리퍼블리카', start='1900') # 토스
df

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,01212921,비바리퍼블리카,,E,사업보고서 (2022.12),20230331003986,비바리퍼블리카,20230331,연
1,01212921,비바리퍼블리카,,E,[기재정정]분기보고서 (2022.09),20230209000527,비바리퍼블리카,20230209,
2,01212921,비바리퍼블리카,,E,[기재정정]반기보고서 (2022.06),20230209000508,비바리퍼블리카,20230209,
3,01212921,비바리퍼블리카,,E,주요사항보고서(유상증자결정),20221116000218,비바리퍼블리카,20221116,
4,01212921,비바리퍼블리카,,E,[기재정정]주요사항보고서(유상증자결정),20221031000418,비바리퍼블리카,20221031,
5,01212921,비바리퍼블리카,,E,주요사항보고서(유상증자결정),20221020000382,비바리퍼블리카,20221020,
6,01212921,비바리퍼블리카,,E,주요사항보고서(유상증자결정),20220825000567,비바리퍼블리카,20220825,
7,01212921,비바리퍼블리카,,E,주요사항보고서(유상증자결정),20220720000316,비바리퍼블리카,20220720,
8,01212921,비바리퍼블리카,,E,분기보고서 (2022.03),20220530000844,비바리퍼블리카,20220530,
9,01212921,비바리퍼블리카,,E,사업보고서 (2021.12),20220331003427,비바리퍼블리카,20220331,연
10,01212921,비바리퍼블리카,,E,연결감사보고서 (2020.12),20210406000710,삼일회계법인,20210406,
11,01212921,비바리퍼블리카,,E,감사보고서 (2020.12),20210406000707,삼일회계법인,20210406,
12,01212921,비바리퍼블리카,,E,감사보고서 (2019.12),20200410003129,삼일회계법인,20200410,
13,01212921,비바리퍼블리카,,E,감사보고서 (2018.12),20190412002776,삼일회계법인,20190412,
14,01212921,비바리퍼블리카,,E,감사보고서 (2017.12),20180413001411,삼일회계법인,20180413,

In [15]:
# 보고서 링크
for ix, row in df.iterrows():
    rcp_no = row['rcept_no']
    print(f'http://dart.fss.or.kr/dsaf001/main.do?rcpNo={rcp_no}')

http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230331003986
http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230209000527
http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230209000508
http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20221116000218
http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20221031000418
http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20221020000382
http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220825000567
http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220720000316
http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220530000844
http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220331003427
http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20210406000710
http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20210406000707
http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20200410003129
http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20190412002776
http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20180413001411

이름으로 확인

In [16]:
comps = dart.company_by_name('하이브')
len(comps)

24

In [19]:
comps[:1]

[{'status': '000',
  'message': '정상',
  'corp_code': '00797373',
  'corp_name': '마포하이브로드파킹(주)',
  'corp_name_eng': 'Mapo Hibroad Parking co., Ltd.',
  'stock_name': '마포하이브로드파킹',
  'stock_code': '',
  'ceo_nm': '도기훈',
  'corp_cls': 'E',
  'jurir_no': '1101114250140',
  'bizr_no': '2208792901',
  'adres': '인천광역시 연수구 인천타워대로 241 24층(송도동,포스코건설사옥)',
  'hm_url': '',
  'ir_url': '',
  'phn_no': '032-748-2754',
  'fax_no': '032-748-2754',
  'induty_code': '41229',
  'est_dt': '20091228',
  'acc_mt': '12'}]

공시목록 가져오기

In [24]:
bighit = dart.list('하이브', start='1900')
bighit

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,01652129,하이브,,E,감사보고서 (2022.12),20230410002201,한성회계법인,20230410,

- 조회를 해보고 정식명칭의 전체 회사명을 사용하십시오. 
- corp_code를 쓰는 것이 가장 확실합니다.

In [25]:
bighit = dart.list('01204056', start='1900')
bighit

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,01204056,하이브,352820,Y,기업설명회(IR)개최(안내공시),20230419800286,하이브,20230419,유
1,01204056,하이브,352820,Y,[기재정정]주요사항보고서(유상증자결정),20230414002159,하이브,20230414,
2,01204056,하이브,352820,Y,주식등의대량보유상황보고서(일반),20230412002524,방시혁,20230412,
3,01204056,하이브,352820,Y,[기재정정]사업보고서 (2022.12),20230403004275,하이브,20230403,연
4,01204056,하이브,352820,Y,정기주주총회결과,20230330801355,하이브,20230330,유
...,...,...,...,...,...,...,...,...,...
155,01204056,하이브,352820,Y,[발행조건확정]증권신고서(지분증권),20200928000122,하이브,20200928,
156,01204056,하이브,352820,Y,연결감사보고서 (2019.12),20200331000038,한영회계법인,20200331,
157,01204056,하이브,352820,Y,감사보고서 (2019.12),20200331000037,한영회계법인,20200331,
158,01204056,하이브,352820,Y,감사보고서 (2018.12),20190319000209,삼일회계법인,20190319,
159,01204056,하이브,352820,Y,감사보고서 (2017.12),20180322000053,삼일회계법인,20180322,

공시 본문가져오기

In [27]:
html_text = dart.document('20200331000038')
html_text[:1000] # 앞부분

'<?xml version="1.0" encoding="utf-8"?>\r\n\r\n\r\n<DOCUMENT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dart3.xsd">\n\n<DOCUMENT-HEADER AEXT-CLASS="Y">\n<DOCUMENT-NAME ACODE="00761">연결감사보고서</DOCUMENT-NAME>\n<FORMULA-VERSION SUBVER="4" ADATE="20190212">3.4</FORMULA-VERSION>\n<COMPANY-NAME AREGCIK="01204056" AACCOUNTTYPE="A">주식회사 빅히트엔터테인먼트</COMPANY-NAME>\n\n<SUMMARY>\n<EXTRACTION ACODE="AUDIT_CIK" AFEATURE="BOTH">00260198</EXTRACTION>\n<EXTRACTION ACODE="SUPV_OPIN" AFEATURE="BOTH">100000000000</EXTRACTION>\n<EXTRACTION ACODE="TOT_ASSETS" AFEATURE="BOTH">362990</EXTRACTION>\n<EXTRACTION ACODE="TOT_DEBTS" AFEATURE="BOTH">189467</EXTRACTION>\n<EXTRACTION ACODE="TOT_SALES" AFEATURE="BOTH">587224</EXTRACTION>\n<EXTRACTION ACODE="TOT_EMPL" AFEATURE="BOTH">228</EXTRACTION>\n<EXTRACTION ACODE="ETC_OTHR_YN" AFEATURE="BOTH">Y</EXTRACTION>\n<EXTRACTION ACODE="POW_OTHR_YN" AFEATURE="BOTH">N</EXTRACTION>\n<EXTRACTION ACODE="ACC_PROF_YN" AFEATURE="BOTH">Y</EXTRACTION>\n<EXTRACTION AC'

### 재무데이터를 데이터프레임으로 읽어오기
- pandas의 read_html()로 페이지에 포함된 표를 손쉽게 DataFrame으로 읽을 수 있습니다.

In [29]:
df_list = pd.read_html(html_text)

C:\Users\jjgus\anaconda3\lib\site-packages\bs4\builder\__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

In [30]:
len(df_list)

142

In [32]:
# 연결재무상태표
df = df_list[14]

remove_text = "&cr;(감사받지 아니한 재무제표)"
df.columns = [col.replace(remove_text, '') for col in df.columns]
df

,과 목,주 석,제15(당) 기말,제15(당) 기말.1,제14(전) 기말,제14(전) 기말.1,제14(전) 기초,제14(전) 기초.1
0,자산,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,유동자산,NaN,NaN,294652316,NaN,171707518.0,NaN,55866023
2,현금및현금성자산,33.0,160780830,NaN,58064738,NaN,29504093,NaN
3,당기손익-공정가치 측정 금융자산,43233.0,-,NaN,36817279,NaN,12004106,NaN
4,매출채권,53033.0,94607697,NaN,49201245,NaN,8208888,NaN
5,기타유동금융자산,633.0,5750441,NaN,12450900,NaN,4999066,NaN
6,기타유동자산,7.0,20541758,NaN,9468209,NaN,1115220,NaN
7,재고자산,8.0,12971590,NaN,5705147,NaN,34650,NaN
8,비유동자산,NaN,NaN,68337520,NaN,33821650.0,NaN,10148197
9,당기손익-공정가치 측정 금융자산,43233.0,1572021,NaN,1892865,NaN,1585539,NaN
10,기타비유동금융자산,633.0,10757572,NaN,3194526,NaN,4479710,NaN
11,공동기업투자,9.0,2327780,NaN,3235619,NaN,-,NaN
12,유형자산,10.0,8184913,NaN,8751498,NaN,1497060,NaN
13,사용권자산,34.0,8654524,NaN,9434846,NaN,1756495,NaN
14,무형자산,11.0,25743454,NaN,6328275,NaN,239583,NaN
15,이연법인세자산,18.0,8523282,NaN,458811,NaN,353020,NaN
16,기타비유동자산,7.0,2573974,NaN,525210,NaN,236790,NaN
17,자산 총계,NaN,NaN,362989836,NaN,205529168.0,NaN,66014220
18,부채,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,유동부채,NaN,NaN,174561335,NaN,105462338.0,NaN,93981466
20,매입채무,3133.0,25342680,NaN,13575752,NaN,-,NaN
21,전환상환우선주부채,143133.0,5143282,NaN,9301013,NaN,5856344,NaN
22,리스부채,313334.0,5289457,NaN,2959831,NaN,1029084,NaN
23,기타유동금융부채,12303133.0,36931276,NaN,33893664,NaN,78151121,NaN
24,당기법인세부채,NaN,15946850,NaN,13264223,NaN,4479798,NaN
25,기타유동부채,13.0,84828925,NaN,32436298,NaN,4465119,NaN
26,유동성장기부채,15.0,1010397,NaN,-,NaN,-,NaN
27,충당부채,16.0,68468,NaN,31557,NaN,-,NaN
28,비유동부채,NaN,NaN,14905580,NaN,12807296.0,NaN,13997870
29,전환상환우선주부채,143133.0,-,NaN,-,NaN,11479292,NaN
30,리스부채,313334.0,2841429,NaN,4878439,NaN,161326,NaN
31,장기차입금,15.0,209790,NaN,-,NaN,-,NaN
32,기타비유동금융부채,123033.0,3000,NaN,-,NaN,159377,NaN
33,순확정급여부채,17.0,4285728,NaN,2990303,NaN,1963663,NaN
34,이연법인세부채,18.0,73294,NaN,593707,NaN,-,NaN
35,기타비유동부채,13.0,5772378,NaN,2592956,NaN,167138,NaN
36,충당부채,16.0,1719961,NaN,1751891,NaN,67074,NaN
37,부채 총계,NaN,NaN,189466915,NaN,118269634.0,NaN,107979336
38,자본,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,지배기업의 소유지분,NaN,NaN,174183579,NaN,87259534.0,NaN,"(41,965,116)"
40,자본금,119.0,834881,NaN,772917,NaN,525026,NaN
41,주식발행초과금,19.0,211100917,NaN,198574802,NaN,265179,NaN
42,기타자본,20.0,4025286,NaN,3522288,NaN,2335460,NaN
43,기타포괄손익누계액,20.0,"(57,982)",NaN,"(67,888)",NaN,"(13,775)",NaN
44,결손금,NaN,"(41,719,523)",NaN,"(115,542,585)",NaN,"(45,077,006)",NaN
45,비지배지분,NaN,NaN,"(660,658)",-,NaN,NaN,-
46,자본 총계,NaN,NaN,173522921,NaN,87259534.0,NaN,"(41,965,116)"
47,부채와 자본 총계,NaN,NaN,362989836,NaN,205529168.0,NaN,66014220

In [33]:
# 연결포괄손익계산서
df = df_list[18]

remove_text = "&cr;(감사받지 아니한 재무제표)"
df.columns = [col.replace(remove_text, '') for col in df.columns]
df

,과 목,주 석,제15기,제15기.1,제14기,제14기.1
0,매출액,2230.0,NaN,587224478,NaN,301371824
1,매출원가,2430.0,NaN,385686888,NaN,189978918
2,매출총이익,NaN,NaN,201537590,NaN,111392906
3,판매비와관리비,2324.0,102795121,NaN,31462308,NaN
4,영업이익,NaN,NaN,98742469,NaN,79930598
5,기타수익,25.0,154231,NaN,97511,NaN
6,기타비용,25.0,510638,NaN,1768914,NaN
7,지분법손실,9.0,907839,NaN,124381,NaN
8,금융수익,2633.0,7490975,NaN,2207145,NaN
9,금융비용,2633.0,6476775,NaN,128791219,NaN
10,법인세비용차감전순손익,NaN,NaN,98492423,NaN,"(48,449,260)"
11,법인세비용,18.0,NaN,26068328,NaN,22016319
12,당기순손익,NaN,NaN,72424095,NaN,"(70,465,579)"
13,지배기업의 소유주 귀속 당기순이익,NaN,NaN,73823063,NaN,"(70,465,579)"
14,비지배지분 귀속 당기순이익,NaN,NaN,"(1,398,968)",NaN,-
15,법인세비용차감후기타포괄손익,NaN,NaN,11384,NaN,"(54,113)"
16,당기손익으로 재분류되는 항목,NaN,NaN,319572,NaN,149134
17,해외사업환산차이,NaN,319572,NaN,149134,NaN
18,후속적으로 당기손익으로 재분류되지 않는 항목,NaN,NaN,"(308,188)",NaN,"(203,247)"
19,순확정급여부채의 재측정요소,NaN,"(308,188)",NaN,"(203,247)",NaN
20,총포괄손익,NaN,NaN,72435479,NaN,"(70,519,692)"
21,지배기업의 소유주 귀속 총포괄손익,NaN,NaN,73832969,NaN,"(70,519,692)"
22,비지배지분 귀속 총포괄손익,NaN,NaN,"(1,397,490)",NaN,-
23,주당순이익 (단위:원),NaN,NaN,NaN,NaN,NaN
24,기본주당순손익,27.0,NaN,47219,NaN,"(54,030)"
25,희석주당순손익,27.0,NaN,42174,NaN,"(54,030)"

In [34]:
# 연결현금흐름표
df = df_list[24]

remove_text = "&cr;(감사받지 아니한 재무제표)"
df.columns = [col.replace(remove_text, '') for col in df.columns]
df

,구 분,주 석,제15기,제15기.1,제14기,제14기.1
0,영업활동으로 인한 현금흐름,NaN,NaN,91713636,NaN,74686749
1,영업으로부터 창출된 현금흐름,28.0,121917870,NaN,88169367,NaN
2,이자의 수취,NaN,175611,NaN,89461,NaN
3,이자의 지급,NaN,"(12,979)",NaN,(117),NaN
4,법인세의 납부,NaN,"(30,366,866)",NaN,"(13,571,962)",NaN
5,투자활동으로 인한 현금흐름,NaN,NaN,12180077,NaN,"(45,068,033)"
6,기타금융자산의 감소,NaN,108939949,NaN,71656309,NaN
7,기타비유동금융자산의 감소,NaN,400019,NaN,86064,NaN
8,유형자산의 처분,NaN,27891,NaN,-,NaN
9,종속기업 취득에 따른 순현금흐름,NaN,"(15,202,551)",NaN,-,NaN
10,관계기업 및 공동기업투자의 취득,NaN,-,NaN,"(3,360,000)",NaN
11,기타금융자산의 증가,NaN,"(65,568,271)",NaN,"(95,971,454)",NaN
12,기타비유동금융자산의 증가,NaN,"(8,031,418)",NaN,"(3,426,566)",NaN
13,유형자산의 취득,NaN,"(4,836,016)",NaN,"(6,609,511)",NaN
14,무형자산의 취득,NaN,"(1,638,699)",NaN,"(7,165,982)",NaN
15,기타비유동자산의 증가,NaN,"(1,910,827)",NaN,"(276,893)",NaN
16,재무활동으로 인한 현금흐름,NaN,NaN,"(1,436,486)",NaN,"(1,393,794)"
17,비지배지분의 증가,NaN,2000000,NaN,-,NaN
18,주식선택권의 행사,NaN,170000,NaN,-,NaN
19,차입금의 차입,NaN,800,NaN,342650,NaN
20,차입금의 상환,NaN,"(190,787)",NaN,"(342,650)",NaN
21,기타금융부채의 감소,NaN,-,NaN,"(24,000)",NaN
22,리스부채의 감소,NaN,"(3,416,500)",NaN,"(1,369,794)",NaN
23,현금및현금성자산의 증가,NaN,NaN,102457227,NaN,28224922
24,외화표시 현금및현금성자산의 환율변동효과,NaN,NaN,258865,NaN,335723
25,기초 현금및현금성자산,NaN,NaN,58064738,NaN,29504093
26,기말 현금및현금성자산,NaN,NaN,160780830,NaN,58064738

# 쿠팡 손익계산서

In [35]:
coupang = dart.list('쿠팡', start='1900')
coupang

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,01019166,쿠팡,,E,연결감사보고서 (2022.12),20230413002431,삼일회계법인,20230413,
1,01019166,쿠팡,,E,감사보고서 (2022.12),20230413002429,삼일회계법인,20230413,
2,01019166,쿠팡,,E,특수관계인에대한출자,20230330001508,쿠팡,20230330,공
3,01019166,쿠팡,,E,특수관계인에대한자산양도,20230329001332,쿠팡,20230329,공
4,01019166,쿠팡,,E,[기재정정]특수관계인에대한부동산임대,20230329001329,쿠팡,20230329,공
...,...,...,...,...,...,...,...,...,...
67,01019166,쿠팡,,E,감사보고서 (2017.12),20180416000060,삼일회계법인,20180416,
68,01019166,쿠팡,,E,연결감사보고서 (2016.12),20170414001794,삼일회계법인,20170414,
69,01019166,쿠팡,,E,감사보고서 (2016.12),20170414001793,삼일회계법인,20170414,
70,01019166,쿠팡,,E,감사보고서 (2015.12),20160414001921,삼일회계법인,20160414,
71,01019166,쿠팡,,E,감사보고서 (2014.12),20150414002045,삼일회계법인,20150414,

In [36]:
# http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20200414000766
html_text = dart.document('20200414000766')

df_list = pd.read_html(html_text)

len(df_list)

C:\Users\jjgus\anaconda3\lib\site-packages\bs4\builder\__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

119

In [42]:
df_list[3]

             0   1
0      쿠팡 주식회사 NaN
1  주주 및 이사회 귀중 NaN

In [37]:
# 연결포괄손익계산서
df_list[15]

                   과 목        주석   제 7 (당)기     제 6 (전)기
0               Ⅰ. 매출액  182324.0    7153094      4354586
1                 매출원가    1924.0    5950017      4142781
2             영업 일반관리비  192324.0    1923606      1339769
3              Ⅱ. 영업손실       NaN  (720,529)  (1,127,964)
4                 기타수익       NaN       1782          436
5                 기타비용       NaN       1481          666
6                 금융수익     520.0      50396        19338
7                 금융비용     520.0      54155        33450
8       Ⅲ. 법인세비용차감전순손실       NaN  (723,987)  (1,142,306)
9             Ⅳ. 법인세비용      14.0      (747)         2331
10            Ⅴ. 당기순손실       NaN  (723,240)  (1,144,637)
11          지배기업 소유주지분       NaN  (723,240)  (1,144,637)
12               비지배지분       NaN          -            -
13           Ⅵ. 기타포괄손실       NaN   (10,504)      (2,826)
14  당기손익으로 재분류되지 않는 항목       NaN   (10,504)      (2,826)
15      순확정급여부채의 재측정요소      13.0   (10,504)      (2,826)
16          Ⅶ. 당기총포괄손실       NaN  (733,744)  (1,147,463)
17          지배기업 소유주지분       NaN  (733,744)  (1,147,463)
18               비지배지분       NaN          -            -